import React from 'react';
import jsPDF from 'jspdf';
import { Download, FileText, X, CheckCircle, AlertTriangle } from 'lucide-react';
import { LoanInput, PredictionResult } from '../types';

interface PdfExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: PredictionResult;
  input: LoanInput;
  applicantName?: string;
}

export const PdfExportModal: React.FC<PdfExportModalProps> = ({
  isOpen,
  onClose,
  result,
  input,
  applicantName = 'Applicant'
}) => {
  if (!isOpen) return null;

  const handleDownload = () => {
    const doc = new jsPDF();

    // Header styling
    doc.setFillColor(30, 58, 138); // Deep Banking Blue
    doc.rect(0, 0, 210, 35, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('LOAN APPROVAL EVALUATION REPORT', 14, 18);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Machine Learning Loan Approval Predictor', 14, 26);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 26);

    // Applicant Details Section
    let y = 48;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('1. APPLICANT FINANCIAL PROFILE', 14, y);

    doc.setLineWidth(0.5);
    doc.setDrawColor(203, 213, 225);
    doc.line(14, y + 2, 196, y + 2);

    y += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const details = [
      [`Applicant Name:`, applicantName, `Gender & Marital:`, `${input.gender}, ${input.married === 'Yes' ? 'Married' : 'Single'}`],
      [`Applicant Monthly Income:`, `$${input.applicant_income.toLocaleString()}`, `Co-Applicant Income:`, `$${input.coapplicant_income.toLocaleString()}`],
      [`Requested Loan Amount:`, `$${input.loan_amount}k ($${(input.loan_amount * 1000).toLocaleString()})`, `Loan Tenure:`, `${input.loan_amount_term} Months`],
      [`Credit History Bureau Score:`, input.credit_history === 1 ? 'Positive (1.0)' : 'Negative / Poor (0.0)', `Property Area Tier:`, input.property_area],
      [`Education Qualification:`, input.education, `Self Employed:`, input.self_employed]
    ];

    details.forEach((row) => {
      doc.setFont('helvetica', 'bold');
      doc.text(row[0], 14, y);
      doc.setFont('helvetica', 'normal');
      doc.text(row[1], 65, y);

      doc.setFont('helvetica', 'bold');
      doc.text(row[2], 110, y);
      doc.setFont('helvetica', 'normal');
      doc.text(row[3], 155, y);
      y += 7;
    });

    // Prediction Outcome Box
    y += 6;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text('2. MACHINE LEARNING DECISION OUTCOME', 14, y);
    doc.line(14, y + 2, 196, y + 2);

    y += 8;
    if (result.is_approved) {
      doc.setFillColor(236, 253, 245);
      doc.rect(14, y, 182, 22, 'F');
      doc.setDrawColor(16, 185, 129);
      doc.rect(14, y, 182, 22, 'S');

      doc.setTextColor(6, 95, 70);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('DECISION: APPROVED', 20, y + 10);
      doc.setFontSize(10);
      doc.text(`Model Confidence Score: ${result.confidence_score}% | Inference Latency: ${result.prediction_time_ms} ms`, 20, y + 17);
    } else {
      doc.setFillColor(255, 241, 242);
      doc.rect(14, y, 182, 22, 'F');
      doc.setDrawColor(244, 63, 94);
      doc.rect(14, y, 182, 22, 'S');

      doc.setTextColor(159, 18, 57);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('DECISION: REJECTED', 20, y + 10);
      doc.setFontSize(10);
      doc.text(`Rejection Probability: ${result.rejection_probability}% | Model Confidence: ${result.confidence_score}%`, 20, y + 17);
    }

    // Key Decision Factors
    y += 30;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('3. KEY INFLUENCING FACTORS', 14, y);
    doc.line(14, y + 2, 196, y + 2);

    y += 8;
    doc.setFontSize(9);
    result.key_factors.forEach((f) => {
      doc.setFont('helvetica', 'bold');
      doc.text(`• ${f.factor}`, 18, y);
      doc.setFont('helvetica', 'normal');
      doc.text(`Impact: ${f.impact} (${f.score})`, 130, y);
      y += 6;
    });

    // Improvement Suggestions
    if (result.suggestions.length > 0) {
      y += 4;
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('4. RECOMMENDED IMPROVEMENT ACTIONS', 14, y);
      doc.line(14, y + 2, 196, y + 2);

      y += 8;
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      result.suggestions.forEach((s) => {
        const splitText = doc.splitTextToSize(`• ${s}`, 175);
        doc.text(splitText, 18, y);
        y += splitText.length * 5;
      });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text('Loan Approval Predictor System | Best Model: Gradient Boosting Classifier (Accuracy: 84.55%)', 14, 285);

    doc.save(`Loan_Application_Report_${applicantName.replace(/\s+/g, '_')}.pdf`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-md animate-fade-in">
      <div className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-2xl border border-slate-200/80 dark:border-white/10 rounded-3xl p-6 max-w-lg w-full shadow-2xl">
        <div className="flex items-center justify-between pb-4 border-b border-slate-200/80 dark:border-white/10">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-blue-500/10 text-blue-600 dark:text-blue-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                Export Evaluation Report
              </h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Download a formal PDF document for {applicantName}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-white/10 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="py-5 space-y-4 text-sm text-slate-600 dark:text-slate-300">
          <div className="p-4 rounded-2xl bg-white/40 dark:bg-slate-950/60 border border-slate-200/60 dark:border-white/10 backdrop-blur-md space-y-2">
            <div className="flex justify-between">
              <span className="text-slate-500 dark:text-slate-400">Applicant:</span>
              <span className="font-semibold text-slate-900 dark:text-white">{applicantName}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500 dark:text-slate-400">Status Outcome:</span>
              <span className={`font-bold ${result.is_approved ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}`}>
                {result.prediction} ({result.confidence_score}%)
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500 dark:text-slate-400">Requested Amount:</span>
              <span className="font-semibold text-slate-900 dark:text-white">${input.loan_amount}k</span>
            </div>
          </div>

          <p className="text-xs text-slate-500 dark:text-slate-400">
            This PDF report includes complete applicant input metadata, ML model confidence score, debt-to-income metrics, decision drivers, and tailored improvement steps.
          </p>
        </div>

        <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-200/80 dark:border-white/10">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-white/10 rounded-2xl transition"
          >
            Cancel
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-5 py-2.5 text-sm font-semibold text-white bg-blue-600 hover:bg-blue-500 rounded-2xl shadow-lg shadow-blue-600/25 transition active:scale-95"
          >
            <Download className="w-4 h-4" />
            Download PDF Report
          </button>
        </div>
      </div>
    </div>
  );
};
